import test from 'node:test';import assert from 'node:assert/strict';
import {mkdtempSync,mkdirSync,writeFileSync,rmSync,symlinkSync} from 'node:fs';import {join} from 'node:path';import {tmpdir} from 'node:os';
import {validateTask,answerQuestion,nextQuestion,taskComplete,saveTask,loadTask} from './task-contract.mjs';
import {portablePath,readContext,sha256} from './safe-paths.mjs';
export const sample=()=>({schema:1,id:'example',revision:1,source:'user:request-1',goal:'Review the code and replace the image',mode:'review',scope:{read:['src/a.js'],write:[]},riskTags:[],excludedActions:['publish'],context:[],questions:[],authority:'host-permissions-required',deliverables:[{id:'code',outcome:'Code review',status:'pending',checks:['Findings linked to source']},{id:'image',outcome:'Correct image',status:'pending',checks:['Human sees selected image']} ]});
function tmp(t){const dir=mkdtempSync(join(tmpdir(),'eidolon-contract-'));t.after(()=>rmSync(dir,{recursive:true,force:true}));return dir;}
test('every deliverable needs separate evidence',()=>{const t=sample();t.deliverables[0]={...t.deliverables[0],status:'verified',evidence:['test:1']};assert.equal(taskComplete(t),false);t.deliverables[1].status='verified';assert.throws(()=>validateTask(t),/evidence/);});
test('pending questions resume and stale answers never apply',()=>{const t=sample();t.questions=[{id:'q1',kind:'preference',state:'pending',question:'Guided or direct?',decision:'onboarding'}];const n=answerQuestion(t,'q1','guided','user:answer-2',1);assert.equal(nextQuestion(n),null);assert.equal(n.questions[0].grantsPermission,false);assert.throws(()=>answerQuestion(n,'q1','yes','user:3',1),/Stale/);});
test('approval records do not mint permissions',()=>{const t=sample();t.questions=[{id:'q1',kind:'approval',state:'pending',question:'Approve this plan?',decision:'build'}];assert.equal(answerQuestion(t,'q1','yes','user:2',1).questions[0].grantsPermission,false);});
test('append-only task revisions reject lost updates',t=>{const root=tmp(t),a=sample();saveTask(root,a);const b={...a,revision:2};saveTask(root,b,1);assert.equal(loadTask(root,a.id).revision,2);assert.throws(()=>saveTask(root,b,1),/changed/);});
for(const path of ['../persona.md','/tmp/persona.md','C:\\persona.md','a/../b','a//b','a%2fb','NUL.md','a:stream','a.','a /b'])test('reject path '+path,()=>assert.throws(()=>portablePath(path)));
test('context hashes detect stale files and bounds refuse large reads',t=>{const root=tmp(t);writeFileSync(join(root,'a.txt'),'first');assert.equal(readContext(root,'a.txt',sha256('first')).text,'first');writeFileSync(join(root,'a.txt'),'changed');assert.throws(()=>readContext(root,'a.txt',sha256('first')),/changed/);assert.throws(()=>readContext(root,'a.txt',null,2),/large/);});
test('directory symlinks cannot source context',t=>{const root=tmp(t),outside=tmp(t);writeFileSync(join(outside,'a.txt'),'outside');try{symlinkSync(outside,join(root,'link'),'junction');}catch(e){if(['EPERM','EACCES'].includes(e.code)){t.skip('OS denied creating symlink fixture');return;}throw e;}assert.throws(()=>readContext(root,'link/a.txt'),/Symlink/);});
